# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='count',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Contador'),
        ),
    ]
