# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_shorturl_url_curta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='url_curta',
        ),
    ]
